org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

# ---- Project coordinates ----
mod_id=steambridge
mod_name=Steam Bridge
mod_group=steambridge

# ---- Platform versions ----
minecraft_version=1.19.2
loader_version=0.16.14
fabric_version=0.76.1+1.19.2

# ---- Runtime deps ----
steamworks4j_version=1.10.0
jna_version=5.14.0
