modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/Ragalikx/steam-bridge-mc/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="Ragalikx"
credits="Ragalikx - author; Valve - Steam SDK (DatagramSockets relay); Daniel Ludwig (code-disaster) - steamworks4j; java-native-access - JNA"

displayTest="IGNORE_ALL_VERSION"
description='''
Steam Bridge - play Minecraft with friends without a public IP.

Players connect via SteamID over P2P or Steam relay - no port-forwarding needed, works behind NAT.
If a direct connection is not possible, traffic is automatically routed through Steam relay servers.

Requires Steam (AppID 480 - Spacewar) to be running.'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="[47.1.106,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="CLIENT"

[[mixins]]
config="steambridge.mixins.json"
